FROM alpine:latest as certs
RUN apk --update add ca-certificates
FROM scratch
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY mquery-${TARGETOS}-${TARGETARCH}${TARGETVARIANT} /mquery
ENTRYPOINT [ "/mquery" ]
